// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_airport_com_d");
	self attach("head_airport_d", "", true);
	self.voice = "russian";
}

precache()
{
	precacheModel("body_airport_com_d");
	precacheModel("head_airport_d");
}
