// THIS FILE IS AUTOGENERATED, DO NOT MODIFY
main()
{
	self setModel("body_keegan_assault_a");
	self attach("head_keegan_assault_a_skull", "", true);
	self.voice = "british";
}

precache()
{
	precacheModel("body_keegan_assault_a");
	precacheModel("head_keegan_assault_a_skull");
}
